name: Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
          apt-get update
          apt-get install -y pandoc
          pip install --upgrade pip
          pip install poetry sphinx sphinx_rtd_theme nbsphinx myst_parser
          poetry export -f requirements.txt --output requirements.txt 
          pip install -r requirements.txt
      - name: build
        run: |
          sphinx-apidoc -f -o ./sphinx/source ./scegot
          sphinx-build ./sphinx/source ./docs
          cp -r docs ./public
          poetry build
          mv dist/*.whl ./public/
      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
